name: Configlet

on:
  workflow_call:
    inputs:
      lint:
        description: "Run configlet lint"
        default: true
        required: false
        type: boolean
      fmt:
        description: "Run configlet fmt"
        default: false
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  configlet:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@main
        # GITHUB_TOKEN is not set when we run the fetch script, because we're in
        # a composite action. Set GH_TOKEN so that `gh release download` can
        # make authenticated requests (it fails otherwise).
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run configlet lint
        run: configlet lint
        if: ${{inputs.lint}}

      - name: Run configlet fmt
        run: configlet fmt
        if: ${{inputs.fmt}}
